"""foundation

Revision ID: a0929dabb70a
Revises: 
Create Date: 2026-08-16 08:18:48.204004
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0929dabb70a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(
        sa.table(
            'agent_profiles',
            sa.column('name', sa.String),
            sa.column('provider', sa.String),
            sa.column('model', sa.String),
            sa.column('effort', sa.String),
            sa.column('permissions', postgresql.JSONB),
            sa.column('default_skills', postgresql.JSONB),
            sa.column('context_policy', postgresql.JSONB),
            sa.column('active', sa.Boolean),
        ),
        [
            {
                'name': name,
                'provider': 'pi',
                'model': None,
                'effort': None,
                'permissions': {},
                'default_skills': [],
                'context_policy': {},
                'active': True,
            }
            for name in ('brief', 'plan', 'implementation', 'escalation')
        ],
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=12), nullable=False),
    sa.Column('repository_path', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('integration_branch', sa.String(length=120), nullable=False),
    sa.Column('next_task_sequence', sa.Integer(), nullable=False),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_commands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('repository_path')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NOT_READY', 'READY', 'IN_PROGRESS', 'TEST', 'DONE', 'FAILED', name='task_status'), nullable=False),
    sa.Column('stage', sa.Enum('CREATED', 'BRIEFING', 'PLANNING', 'AWAITING_APPROVAL', 'QUEUED', 'PREPARING_GIT', 'IMPLEMENTING', 'VALIDATING', 'ESCALATING', 'BLOCKED', 'COMPLETE', name='task_stage'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_source', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_plan_revision', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(length=240), nullable=True),
    sa.Column('worktree_path', sa.Text(), nullable=True),
    sa.Column('checkpoint_sha', sa.String(length=64), nullable=True),
    sa.Column('active_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_profile_id'], ['agent_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_session_id', sa.String(length=160), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('checkpoint_sha', sa.String(length=64), nullable=True),
    sa.Column('diff_hash', sa.String(length=64), nullable=True),
    sa.Column('error_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_task_id'), 'attempts', ['task_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_task_id'), 'escalations', ['task_id'], unique=False)
    op.create_table('events',
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_events_task_id'), 'events', ['task_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('plan_revisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('brief_markdown', sa.Text(), nullable=False),
    sa.Column('plan_markdown', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'revision')
    )
    op.create_index(op.f('ix_plan_revisions_task_id'), 'plan_revisions', ['task_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_task_id'), 'validation_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_runs_task_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_plan_revisions_task_id'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_task_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_escalations_task_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_attempts_task_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
